kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgressonar
  annotations:
     volume.beta.kubernetes.io/storage-class: "example-nfs"
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.124.20
    path: "/nfs/sonar-postgre"
 
